### ISSUE TITLE
error when using with nextcloud

### ISSUE THREAD

**Issue by syswombat** [carlos22/carddav2fb#29]
Hello
what did i wrong? from nextcloud contact addressbock.
have a nice day

> Retrieving VCards from all CardDAV server(s):
>  [0]: http://nextcloud.kozo.ch/remote.php/dav/addressbooks/users/vincent/Fritzphone/ PHP Fatal error:  Uncaught Exception: Woops, something's gone wrong! The CardDAV server returned the http status code 401. in /root/carddav2fb/lib/CardDAV-PHP/carddav.php:349
> Stack trace:
> #0 /root/carddav2fb/carddav2fb.php(217): CardDavPHP\CardDavBackend->get()
> #1 /root/carddav2fb/carddav2fb.php(79): CardDAV2FB->get_carddav_entries()
> #2 {main}
>   thrown in /root/carddav2fb/lib/CardDAV-PHP/carddav.php on line 349

**Comment by carlos22** [comment]
I think your credentials are wrong? 401 means you are not authenticated: https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Client_errors
