### ISSUE TITLE
Issues with Fritz Box 7.29

### ISSUE THREAD

**Issue by mkstdAnna** [carlos22/carddav2fb#37]
Hello everyone! 

We successfully used the script until a couple of weeks ago with our Fritz Box. Unfortunately it's not working anymore, new contacts are not synced. 

Any idea what might causes the problem? Seems like its no longer compatible with the current PHP. Does anyone have an solution or idea?

Thank you! 

```
makeadmin@GardeStation:/$ /bin/php /volume1/Bureau/Bureau/XX-Fest/moco2fritz/carddav2fb.php
PHP Warning:  PHP Startup: ftp: Unable to initialize module
Module compiled with module API=20131226
PHP    compiled with module API=20180731
These options need to match
 in Unknown on line 0
carddav2fb.php 1.11 (2016-05-12) - CardDAV to FRITZ!Box phonebook conversion tool
Copyright (c) 2012-2016 Karl Glatz, Martin Rost, Jens Maus, Johannes Freiburger

Retrieving VCards from all CardDAV server(s):
 [0]: https://makestudio.mocoapp.com/carddav/principal/addressbook PHP Fatal error:  Uncaught Exception: Woops, something's gone wrong! The CardDAV server returned the http status code 401. in /volume1/Bureau/Bureau/XX-Fest/moco2fritz/lib/CardDAV-PHP/carddav.php:349
Stack trace:
#0 /volume1/Bureau/Bureau/XX-Fest/moco2fritz/carddav2fb.php(217): CardDavPHP\CardDavBackend->get()
#1 /volume1/Bureau/Bureau/XX-Fest/moco2fritz/carddav2fb.php(79): CardDAV2FB->get_carddav_entries()
#2 {main}
  thrown in /volume1/Bureau/Bureau/XX-Fest/moco2fritz/lib/CardDAV-PHP/carddav.php on line 349

Fatal error: Uncaught Exception: Woops, something's gone wrong! The CardDAV server returned the http status code 401. in /volume1/Bureau/Bureau/XX-Fest/moco2fritz/lib/CardDAV-PHP/carddav.php:349
Stack trace:
#0 /volume1/Bureau/Bureau/XX-Fest/moco2fritz/carddav2fb.php(217): CardDavPHP\CardDavBackend->get()
#1 /volume1/Bureau/Bureau/XX-Fest/moco2fritz/carddav2fb.php(79): CardDAV2FB->get_carddav_entries()
#2 {main}
  thrown in /volume1/Bureau/Bureau/XX-Fest/moco2fritz/lib/CardDAV-PHP/carddav.php on line 349
```

**Comment by carlos22** [comment]
The script is very old and was not updated for a long time. But I think the FTP module is missing. You might need to install (and enable) it.
